###root api
GET http://localhost:8000/api/v1/game/number
###Post the numbers
POST http://localhost:8000/api/v1/game/number
Content-Type: application/json

{
    "urNumber":"5908430",
    "partnerNumber":"1576536300"
}
### get fblogins 
GET http://localhost:8000/api/v1/game/fblogins
###Post fblogins
POST http://localhost:8000/api/v1/game/fblogins
Content-Type: application/json

{
    "userName":"pradeep",
    "password":"fkdlufd"
}
### get facebooklogins 
GET http://localhost:8000/api/v1/game/fblogins
###Post facebooklogins
POST http://localhost:8000/api/v1/game/fblogins
Content-Type: application/json

{
    "userName":"pradeep",
    "password":"fkdlufd"
}
### get facebooklogins 
GET http://localhost:8000/api/v1/game/confirmcode
###Post facebooklogins
POST http://localhost:8000/api/v1/game/confirmcode
Content-Type: application/json

{
   "confirmCode":"57354"
}
###root api POST
GET http://localhost:8000/